version: "3"

services:
  proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:latest
    environment:
      DEFAULT_HOST: ${DEFAULT_HOST}
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs
      # - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./log:/var/log
    ports:
      - ${APP_PORT:-80}:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
    restart: always
    depends_on:
      - proxy
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - /etc/acme.sh
